[] Migrate UI components to new monorepo
cpalmer-ostmodern/npm-mono pull request #6
Opened 2023-02-14 15:57 UTC by MikeOstmodern

**Task(s)**
- Migrate components from NX to NPM Workspace

2023-02-14 15:59 UTC, MikeOstmodern commented on @local/ui/src/components/atoms/article/article-video-image/article-video-image.component.tsx
> +    </svg>
This is a custom SVG on the live site so can't convert to icomoon

2023-02-17 11:41 UTC, cpalmer-ostmodern commented on @local/ui/src/components/atoms/article/article-video-image/article-video-image.component.tsx
> +    </svg>
ok, in that case let's pass this svg down as a prop to avoid the component library having to bundle any svg resources

2023-02-17 11:48 UTC, cpalmer-ostmodern requested changes

2023-02-17 11:48 UTC, cpalmer-ostmodern commented on @local/ui/index.tsx
> -import { TopicButton } from "./dist/lib";
MUST: let's remove the DS_Store files from above as they are only used by .git cli and may hold stale changes.

2023-02-17 11:48 UTC, cpalmer-ostmodern commented on @local/ui/index.tsx
> -import { TopicButton } from "./dist/lib";
maybe just add .DS_Store to the .gitignore in ui too

2023-02-17 11:48 UTC, cpalmer-ostmodern commented on src/tailwind.config.js
>  };
delete the yarn lock too please as we are using npm now

2023-02-17 12:31 UTC, MikeOstmodern commented on @local/ui/index.tsx
> -import { TopicButton } from "./dist/lib";
Ah I think these are the deletions https://github.com/cpalmer-ostmodern/npm-mono/pull/6/commits/5cd2a40d39bed90138c8f49bf2eba62cc50cf6b1 @cpalmer-ostmodern

2023-02-17 12:32 UTC, MikeOstmodern commented on src/tailwind.config.js
>  };
Thanks, removed https://github.com/cpalmer-ostmodern/npm-mono/pull/6/commits/7179576a4346b861406a4da99a372da7b062651d

2023-02-17 12:55 UTC, cpalmer-ostmodern requested changes
sorry couple more small things

2023-02-17 12:55 UTC, cpalmer-ostmodern commented on @local/ui/src/components/atoms/sub-menu-counter/sub-menu-counter.component.tsx
> +  totalLinks: number | undefined;
optional totalLinks please

2023-02-17 12:55 UTC, cpalmer-ostmodern commented on @local/ui/src/components/molecules/menu/menu-magazine-cover/menu-magazine-cover.component.tsx
> +          <div className="flex justify-end gap-6 md:justify-between">
let's move the tailwind names to props as they wont be detected unless in the safe list of the tailwind config

2023-02-17 13:13 UTC, MikeOstmodern commented on @local/ui/src/components/molecules/menu/menu-magazine-cover/menu-magazine-cover.component.tsx
> +          <div className="flex justify-end gap-6 md:justify-between">
Happy to do this now but was was going to suggest a sub-task in the cleanup ticket to remove as many of those safelisted classes in the config file as possible. Want to bundle it all into that set of work? @cpalmer-ostmodern

2023-02-17 13:14 UTC, MikeOstmodern commented on @local/ui/src/components/atoms/sub-menu-counter/sub-menu-counter.component.tsx
> +  totalLinks: number | undefined;
Thanks, good spot - https://github.com/cpalmer-ostmodern/npm-mono/pull/6/commits/d000fd66d3c4f47dac05ddd9c9216aec7487c80f

2023-02-17 13:21 UTC, MikeOstmodern commented on @local/ui/src/components/atoms/article/article-video-image/article-video-image.component.tsx
> +    </svg>
Just for clarity this is part of a component that adjusts fill color based on the `active` prop state:
```
function PlayIcon({ active = false }) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width={72} height={72} fill="none">
      <path fill="#fff" d="M0 0h72v72H0z" />
      <path
        d="M27.806 20.781 49.686 36l-21.88 15.219V20.781Z"
        fill={active ? '#212121' : ''}
        stroke="#212121"
        strokeWidth={1.5}
      />
    </svg>
  );
}
```

If the svg is inline like this does it still complied as an asset?

2023-02-17 13:21 UTC, MikeOstmodern commented on @local/ui/src/components/atoms/article/article-video-image/article-video-image.component.tsx
> +    </svg>
I can refactor so that we pass down an asset for both states as a prop instead if so though @cpalmer-ostmodern

2023-02-17 13:39 UTC, cpalmer-ostmodern commented on @local/ui/src/components/molecules/menu/menu-magazine-cover/menu-magazine-cover.component.tsx
> +          <div className="flex justify-end gap-6 md:justify-between">
ok sure

2023-02-17 13:40 UTC, cpalmer-ostmodern commented on @local/ui/src/components/atoms/article/article-video-image/article-video-image.component.tsx
> +    </svg>
ok, let's refactor in the clean up

2023-02-17 13:40 UTC, cpalmer-ostmodern approved these changes

2023-02-17 13:41 UTC, merged